-- ============================================================
-- KAPA BANK — DATABASE MIGRATION V2 (MULTI-USER & AUDIT LOG)
-- ============================================================
-- IMPORTANT: This script is additive and non-destructive.
-- Existing tables (customers, bank_accounts, bank_transactions, bank_transfers)
-- and their data remain completely intact.

-- 1. USERS & AUTHENTICATION TABLE
-- Stores credentials and role assignments for Customers and Admins.
-- Passwords are stored exclusively as secure one-way Werkzeug hashes.
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'CUSTOMER' NOT NULL,
    customer_id NUMBER,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT fk_user_customer FOREIGN KEY (customer_id) 
        REFERENCES customers(customer_id) ON DELETE CASCADE,
    CONSTRAINT chk_user_role CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT chk_user_active CHECK (is_active IN (0, 1))
);

-- 2. AUDIT LOG TABLE
-- Logs security-sensitive and transactional actions for compliance & security.
CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50),
    entity_id NUMBER,
    details VARCHAR2(500),
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) 
        REFERENCES users(user_id) ON DELETE SET NULL
);

-- 3. SUPPORTING INDEXES
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_customer ON users(customer_id);
CREATE INDEX idx_audit_user ON audit_log(user_id);
CREATE INDEX idx_audit_created ON audit_log(created_at DESC);
CREATE INDEX idx_accounts_customer ON bank_accounts(customer_id);

-- Optional comment documentation on tables & columns
COMMENT ON TABLE users IS 'User authentication and role mapping for KAPA Bank portal';
COMMENT ON COLUMN users.role IS 'User role: CUSTOMER (self-service portal) or ADMIN (system operations)';
COMMENT ON COLUMN users.customer_id IS 'FK to customers table (NULL for system administrators)';
COMMENT ON TABLE audit_log IS 'Immutable audit trail of authentication and sensitive banking activities';
