-- BANK TRANSACTION MANAGEMENT SYSTEM

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    phone VARCHAR2(15) NOT NULL,
    address VARCHAR2(200),
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT uq_customer_phone UNIQUE (phone)
);

CREATE TABLE bank_accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMBER NOT NULL,
    account_number VARCHAR2(20) NOT NULL,
    account_type VARCHAR2(20) NOT NULL,
    balance NUMBER(15,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_bank_accounts PRIMARY KEY (account_id),
    CONSTRAINT fk_account_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),
    CONSTRAINT uq_account_number UNIQUE (account_number),
    CONSTRAINT chk_account_type CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    CONSTRAINT chk_account_balance CHECK (balance >= 0),
    CONSTRAINT chk_account_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);

CREATE TABLE bank_transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transaction_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'COMMITTED' NOT NULL,
    CONSTRAINT pk_bank_transactions PRIMARY KEY (transaction_id),
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id)
        REFERENCES bank_accounts(account_id),
    CONSTRAINT chk_transaction_type CHECK (
        transaction_type IN (
            'DEPOSIT',
            'WITHDRAWAL',
            'TRANSFER_IN',
            'TRANSFER_OUT'
        )
    ),
    CONSTRAINT chk_transaction_amount CHECK (amount > 0),
    CONSTRAINT chk_transaction_status CHECK (
        status IN ('COMMITTED', 'ROLLED_BACK', 'FAILED')
    )
);

CREATE TABLE bank_transfers (
    transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    from_account NUMBER NOT NULL,
    to_account NUMBER NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transfer_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'COMMITTED' NOT NULL,
    CONSTRAINT pk_bank_transfers PRIMARY KEY (transfer_id),
    CONSTRAINT fk_transfer_from FOREIGN KEY (from_account)
        REFERENCES bank_accounts(account_id),
    CONSTRAINT fk_transfer_to FOREIGN KEY (to_account)
        REFERENCES bank_accounts(account_id),
    CONSTRAINT chk_transfer_amount CHECK (amount > 0),
    CONSTRAINT chk_transfer_status CHECK (
        status IN ('COMMITTED', 'ROLLED_BACK', 'FAILED')
    ),
    CONSTRAINT chk_different_accounts CHECK (from_account <> to_account)
);